# Generated by Django 3.2.18 on 2023-04-20 03:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usr',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='用户编号')),
                ('username', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='登录名')),
                ('password', models.CharField(max_length=50, verbose_name='登录密码')),
                ('nickname', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='用户昵称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='UsrProfile',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, verbose_name='扩展资料编号')),
                ('usr', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.usr')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('gender', models.CharField(blank=True, choices=[('0', '女'), ('1', '男')], max_length=1, null=True, verbose_name='性别')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='邮箱')),
                ('status', models.CharField(choices=[('2', '删除'), ('0', '正常'), ('1', '锁定')], default=0, max_length=5, verbose_name='用户状态')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='个人介绍')),
                ('fans_count', models.IntegerField(default=0, verbose_name='粉丝数量')),
                ('visited_count', models.IntegerField(default=0, verbose_name='访问次数')),
                ('article_count', models.IntegerField(default=0, verbose_name='文章篇数')),
                ('collected_count', models.IntegerField(default=0, verbose_name='收藏总数')),
                ('liked_count', models.IntegerField(default=0, verbose_name='喜欢总数')),
            ],
            options={
                'verbose_name': '用户扩展资料',
                'verbose_name_plural': '用户扩展资料',
            },
        ),
    ]
