# Generated by Django 3.2.18 on 2023-04-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usrprofile',
            name='articles_collected',
            field=models.ManyToManyField(related_name='articlecollected', to='article.Article'),
        ),
        migrations.AddField(
            model_name='usrprofile',
            name='articles_liked',
            field=models.ManyToManyField(related_name='articleliked', to='article.Article'),
        ),
        migrations.AddField(
            model_name='usrprofile',
            name='usrs_liked',
            field=models.ManyToManyField(blank=True, related_name='_account_usrprofile_usrs_liked_+', to='account.UsrProfile'),
        ),
    ]
