# Generated by Django 3.2.18 on 2023-04-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usrprofile',
            old_name='collected_count',
            new_name='article_collected_count',
        ),
        migrations.RenameField(
            model_name='usrprofile',
            old_name='liked_count',
            new_name='article_liked_count',
        ),
        migrations.AddField(
            model_name='usrprofile',
            name='fans',
            field=models.ManyToManyField(blank=True, related_name='my_fans', to='account.UsrProfile'),
        ),
        migrations.AddField(
            model_name='usrprofile',
            name='usrs_liked_count',
            field=models.IntegerField(default=0, verbose_name='关注数量'),
        ),
        migrations.AlterField(
            model_name='usrprofile',
            name='status',
            field=models.CharField(choices=[('1', '锁定'), ('0', '正常'), ('2', '删除')], default=0, max_length=5, verbose_name='用户状态'),
        ),
        migrations.AlterField(
            model_name='usrprofile',
            name='usrs_liked',
            field=models.ManyToManyField(blank=True, related_name='users_you_liked', to='account.UsrProfile'),
        ),
    ]
