# Generated by Django 3.2.18 on 2023-04-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230420_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrprofile',
            name='status',
            field=models.CharField(choices=[('2', '删除'), ('1', '锁定'), ('0', '正常')], default=0, max_length=5, verbose_name='用户状态'),
        ),
    ]
