# Generated by Django 3.2.18 on 2025-04-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_usrprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrprofile',
            name='status',
            field=models.CharField(choices=[('2', '删除'), ('0', '正常'), ('1', '锁定')], default=0, max_length=5, verbose_name='用户状态'),
        ),
    ]
