# Generated by Django 3.2.18 on 2023-04-20 03:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='文章编号')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('readed_count', models.IntegerField(default=0, verbose_name='阅读次数')),
                ('admired_count', models.IntegerField(default=0, verbose_name='点赞次数')),
                ('liked_count', models.IntegerField(default=0, verbose_name='喜欢次数')),
                ('collected_count', models.IntegerField(default=0, verbose_name='收藏次数')),
                ('commented_count', models.IntegerField(default=0, verbose_name='评论次数')),
                ('up_time', models.DateTimeField(auto_now=True, verbose_name='上次修改时间')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=2, verbose_name='当前状态')),
                ('tag_name', models.CharField(default='default', max_length=20, verbose_name='标签标题')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.usr')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-pub_time', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['title'], name='article_art_title_d15895_idx'),
        ),
    ]
