@startuml

title __UTILS's Class Diagram__\n

'  namespace com.wxc.campuslife {
'    namespace utils {
'      class com.wxc.campuslife.utils.AccessServerData {
'          + collectArticle()
'          + delArticle()
'          + fans()
'          + followUsers()
'          + getArticleByAuthor()
'          + getArticleByTag()
'          + getArticleRead()
'          + getCommentByArticle()
'          + getSubComment()
'          + getUserProfile()
'          + getUserid()
'          + likeArticle()
'          + publishSubComment()
'          + publishTopComment()
'          + updateArticle()
'          + updateUserProfile()
'          + userFollow()
'      }
'    }
'  }
'
'
'  namespace com.wxc.campuslife {
'    namespace utils {
'      class com.wxc.campuslife.utils.AlarmManagerUtils {
'          {static} + am : AlarmManager
'          {static} + pendingIntent : PendingIntent
'          {static} - TIME_INTERVAL : long
'          - calendar : Calendar
'          - context : Context
'          {static} - instance : AlarmManagerUtils
'          + alarmManagerStartWork()
'          + createAlarmManager()
'          + createAlarmManagerNow()
'          {static} + getInstance()
'          - AlarmManagerUtils()
'      }
'    }
'  }
'
'
'
'  namespace com.wxc.campuslife {
'    namespace utils {
'      class com.wxc.campuslife.utils.MyApplication {
'          {static} - context : Context
'          {static} + getContext()
'          + onCreate()
'      }
'    }
'  }
'
'  namespace com.wxc.campuslife {
'    namespace utils {
'      class com.wxc.campuslife.utils.FormatConvert {
'          + datetocal()
'      }
'    }
'  }


  namespace com.wxc.campuslife {
    namespace utils {
      class com.wxc.campuslife.utils.dbHelper {
          + dbHelper()
          + onCreate()
          + onUpgrade()
      }
    }
  }




'  com.wxc.campuslife.utils.MyApplication -up-|> android.app.Application
  com.wxc.campuslife.utils.dbHelper -up-|> android.database.sqlite.SQLiteOpenHelper


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
